### ISSUE TITLE
port encointer client for parachain

### ISSUE THREAD

**Issue by brenzi** [encointer/encointer-parachain#3]
Because the parachain template still doesn't use MultiAddress, we need to adapt substrate-api-client as well as encointer-client to work with the encointer-collator

The strategy:
* have the client in its own repo encointer/encointer-client
* refactor encointer-client crate to be a library offering all chain-specific functions
* separate encointer-cli-client crate for a CLI binary
* make cli client support all chains with a single binary: Gesell, Cantillon, Parachain. Identify chain by metadata and use types accordingly (at least the `Address` type)
  * this will probably require making substrate-api-client more generic

**Comment by clangenb** [comment]
Summary of some research:

*  **Address Type:** The address type itself is not exposed in the metadata. This needs to be configured manually as explained in the [polkadot-js FAQ](https://polkadot.js.org/docs/api/FAQ).
 
* **Be More Generic** Currently, it is only the `Address` type that differs, but for flexibility I think we should make the `substrate-api-client` generic over a [Runtime](https://github.com/paritytech/substrate-subxt/blob/3c46002e670d3b3e285c5cf53cc3e9852d6924cf/src/runtimes.rs#L160) trait  as done in subxt, which defines all the primitives. So third-party developers can implement the trait themselves for a custom runtime. I would go for this approach. The `substrate-api-client` would look like this: `ApiClient<T: Runtime>`. 

* **Runtime Metadata:** This could be problematic too because the `substrate-api-client` infers its metadata based on the [RuntimeMetadataPrefixed](https://github.com/paritytech/substrate/blob/9b08105b8c7106d723c4f470304ad9e2868569d9/frame/metadata/src/lib.rs) defined in substrate, which always deprecates earlier versions. However, this is only a potential problem in the future, as our nodes and the parachain-template currently use the same metadata version.

### Implication for encointer-client
* The cli client can easily support all the chains with different implementations of this newly introduced `Runtime` trait for each chain respectively.
* We  hope that we maintain the same metadata version for all our chains and address that problem if the time comes.

**Comment by brenzi** [comment]
chain specific trait does not help because we're still hard-coding the runtime into the binary. My goal would've been to share the same binary for different chains. 
Probably, Gesell and Cantillon might merge into one anyway: Offering all pallets onchain too, so communities can decide if they want to deploy onchain or on TEE (immature thought).

What we could do:
1. use MultiAddress for parachain -> so we have compatibility
2. use Gesell client, but add substratee-pallet to Gesell
3. add subcommand `trusted` for all the TEE stuff

thoughts?

**Comment by clangenb** [comment]
1. Should be done anyhow, I think. Roccoco does use the MultiAddress too.

I need to think about the other 2. and 3.

**Comment by clangenb** [comment]
Regarding chain specific trait. I did understand you correctly. We can pass the concrete `Runtime` trait implementation at runtime and not at compile time. This, however, implies that the `Runtime` trait needs to be [object safe](https://github.com/rust-lang/rfcs/blob/master/text/0255-object-safety.md).

**Comment by clangenb** [comment]
> Probably, Gesell and Cantillon might merge into one anyway: Offering all pallets onchain too, so communities can decide if they want to deploy onchain or on TEE (immature thought).

If you think this is going happen, we should add the subcommand `trusted`, as there is no way for the binary to know if it should call the TEE or the node.

**Comment by clangenb** [comment]
Conclusively, my suggestion would be:
1. Update parachain to use MultiAddress. It [deprecates](https://github.com/paritytech/substrate/pull/7380) the old Address type.
2. Make the api-client `ApiClient<dyn Runtime>`. it does not take long to figure out if this is possible. If we can constrain the types we want to add to our `Runtime` trait with `: Sized`, it should work. Fall back to your suggestion 2. if this is not possible.
3. Add `trusted` subcommand according to my reasoning above.

**Comment by clangenb** [comment]
> use Gesell client, but add substratee-pallet to Gesell

Why does it matter whether Gesell contains the substratee-pallet? I believe all the relevant information is found in the metadata

**Comment by clangenb** [comment]
> Make the api-client ApiClient<dyn Runtime>. it does not take long to figure out if this is possible. If we can constrain the types we want to add to our Runtime trait with : Sized, it should work.

I just realized, there is no need for this if we update the parachain...

**Comment by brenzi** [comment]
as the parachain now works with encointer-client-notee, shall we close this issue and postpone moving it to its own crate?

**Comment by clangenb** [comment]
I agree.
